# ATN-XPIHandler common environment variables

## CAUTION: Do NOT source this directly!
## Source 'env.sh' instead.

## Additionally, if you need to override any variables here, export them to your shell manually or use `env_override.sh`.
## Do NOT edit this file directly.

# If variables are defined with a custom `env_override.sh` file (located at the root project directory), let's use those
## These need to be set first, to ensure that they don't interfere with certain variables
readonly ATNXPI_ENV_OVERRIDE="${ATNXPI_ROOT}/env_override.sh"
if [[ -f "${ATNXPI_ENV_OVERRIDE}" ]]; then
    source "${ATNXPI_ENV_OVERRIDE}"
fi

# ATN-XPIHandler

# Scripts directory
readonly ATNXPI_SCRIPTS="${ATNXPI_ROOT}/scripts"
export ATNXPI_SCRIPTS

# Templates
readonly ATNXPI_TEMPLATES="${ATNXPI_ROOT}/templates"
export ATNXPI_TEMPLATES

## ATN-XPIHandler utilities
readonly ATNXPI_UTILS="${ATNXPI_SCRIPTS}/utilities.sh"
export ATNXPI_UTILS

# Build directory
readonly ATNXPI_BUILD_DEFAULT="${ATNXPI_ROOT}/build"
if [[ -z "${ATNXPI_BUILD+x}" ]]; then
    ATNXPI_BUILD="${ATNXPI_BUILD_DEFAULT}"
fi
readonly ATNXPI_BUILD
export ATNXPI_BUILD

# Set our platform and OS
readonly ATNXPI_ENV_HELPERS="${ATNXPI_SCRIPTS}/env_helpers.sh"
export ATNXPI_ENV_HELPERS
source "${ATNXPI_ENV_HELPERS}"

# Version info
readonly ATNXPI_VERSIONS="${ATNXPI_SCRIPTS}/versions.sh"
export ATNXPI_VERSIONS

# Outputs directory
readonly ATNXPI_OUTPUTS_DEFAULT="${ATNXPI_ROOT}/outputs"
if [[ -z "${ATNXPI_OUTPUTS+x}" ]]; then
    ATNXPI_OUTPUTS="${ATNXPI_OUTPUTS_DEFAULT}"
fi
readonly ATNXPI_OUTPUTS
export ATNXPI_OUTPUTS

# ATN-XPIHandler add-on ID
readonly ATNXPI_ADDON_ID_DEFAULT='atn-xpihandler-direct@celenity.dev'
if [[ -z "${ATNXPI_ADDON_ID+x}" ]]; then
    ATNXPI_ADDON_ID="${ATNXPI_ADDON_ID_DEFAULT}"
fi
readonly ATNXPI_ADDON_ID
export ATNXPI_ADDON_ID

# ATN-XPIHandler (ATN) add-on ID
readonly ATNXPI_ATN_ADDON_ID_DEFAULT='atn-xpihandler@celenity.dev'
if [[ -z "${ATNXPI_ATN_ADDON_ID+x}" ]]; then
    ATNXPI_ATN_ADDON_ID="${ATNXPI_ATN_ADDON_ID_DEFAULT}"
fi
readonly ATNXPI_ATN_ADDON_ID
export ATNXPI_ATN_ADDON_ID

# ATN-XPIHandler update URL
readonly ATNXPI_UPDATE_URL_DEFAULT='https:/releases.celenity.dev/addons/updates.json'
if [[ -z "${ATNXPI_UPDATE_URL+x}" ]]; then
    # By default, use our update URL
    ATNXPI_UPDATE_URL="${ATNXPI_UPDATE_URL_DEFAULT}"
fi
readonly ATNXPI_UPDATE_URL
export ATNXPI_UPDATE_URL

# Should we create a log file for build.sh? (Default)
readonly ATNXPI_LOG_BUILD_DEFAULT=1
if [[ -z "${ATNXPI_LOG_BUILD+x}" ]]; then
    ATNXPI_LOG_BUILD="${ATNXPI_LOG_BUILD_DEFAULT}"
fi
readonly ATNXPI_LOG_BUILD
export ATNXPI_LOG_BUILD

# Directory where we should store log files (if logging is desired)
readonly ATNXPI_LOG_DIR_DEFAULT="${ATNXPI_BUILD}/logs"
if [[ -z "${ATNXPI_LOG_DIR+x}" ]]; then
    ATNXPI_LOG_DIR="${ATNXPI_LOG_DIR_DEFAULT}"
fi
readonly ATNXPI_LOG_DIR
export ATNXPI_LOG_DIR

# GNU awk
if [[ "${ATNXPI_OS}" == 'osx' ]]; then
    readonly ATNXPI_AWK_DEFAULT='gawk'
else
    readonly ATNXPI_AWK_DEFAULT='awk'
fi
if [[ -z "${UBIRD_AWK+x}" ]]; then
    ATNXPI_AWK="${ATNXPI_AWK_DEFAULT}"
fi
readonly ATNXPI_AWK
export ATNXPI_AWK

# GNU sed
if [[ "${ATNXPI_OS}" == 'osx' ]]; then
    readonly ATNXPI_SED_DEFAULT='gsed'
else
    readonly ATNXPI_SED_DEFAULT='sed'
fi
if [[ -z "${ATNXPI_SED+x}" ]]; then
    ATNXPI_SED="${ATNXPI_SED_DEFAULT}"
fi
readonly ATNXPI_SED
export ATNXPI_SED

# GNU tar
if [[ "${ATNXPI_OS}" == 'osx' ]]; then
    readonly ATNXPI_TAR_DEFAULT='gtar'
else
    readonly ATNXPI_TAR_DEFAULT='tar'
fi
if [[ -z "${ATNXPI_TAR+x}" ]]; then
    ATNXPI_TAR="${ATNXPI_TAR_DEFAULT}"
fi
readonly ATNXPI_TAR
export ATNXPI_TAR

# We've now set our environment variables...
readonly ATNXPI_SET_ENVS=1
export ATNXPI_SET_ENVS
