# ATN-XPIHandler common environment variables

## CAUTION: Do NOT source this directly!
## Source 'env.sh' instead.

## Additionally, if you need to override any variables here, export them to your shell manually or use `env_override.sh`.
## Do NOT edit this file directly.

# If variables are defined with a custom `env_override.sh` file (located at the root project directory), let's use those
## These need to be set first, to ensure that they don't interfere with certain variables
ATNXPI_ENV_OVERRIDE="${ATNXPI_ROOT}/env_override.sh"
if [[ -f "${ATNXPI_ENV_OVERRIDE}" ]]; then
    source "${ATNXPI_ENV_OVERRIDE}"
fi

# ATN-XPIHandler

# Scripts directory
export ATNXPI_SCRIPTS="${ATNXPI_ROOT}/scripts"

# Build directory
ATNXPI_BUILD_DEFAULT="${ATNXPI_ROOT}/build"
if [[ -z "${ATNXPI_BUILD+x}" ]]; then
    export ATNXPI_BUILD="${ATNXPI_BUILD_DEFAULT}"
fi

# Set our platform, OS, and architecture
export ATNXPI_ENV_HELPERS="${ATNXPI_SCRIPTS}/env_helpers.sh"
source "${ATNXPI_ENV_HELPERS}"

# Version info
export ATNXPI_VERSIONS="${ATNXPI_SCRIPTS}/versions.sh"

# Build resources directory
export ATNXPI_BUILD_RESOURCES="${ATNXPI_ROOT}/build-resources"

# Outputs directory
ATNXPI_OUTPUTS_DEFAULT="${ATNXPI_ROOT}/outputs"
if [[ -z "${ATNXPI_OUTPUTS+x}" ]]; then
    export ATNXPI_OUTPUTS="${ATNXPI_OUTPUTS_DEFAULT}"
fi

# Should we create a log file for package.sh? (Default)
ATNXPI_LOG_PACKAGE_DEFAULT=1
if [[ -z "${ATNXPI_LOG_PACKAGE+x}" ]]; then
    export ATNXPI_LOG_PACKAGE="${ATNXPI_LOG_PACKAGE_DEFAULT}"
fi

# Directory where we should store log files (if logging is desired)
ATNXPI_LOG_DIR_DEFAULT="${ATNXPI_BUILD}/logs"
if [[ -z "${ATNXPI_LOG_DIR+x}" ]]; then
    export ATNXPI_LOG_DIR="${ATNXPI_LOG_DIR_DEFAULT}"
fi

# GNU sed
if [[ "${ATNXPI_OS}" == 'osx' ]]; then
    ATNXPI_SED_DEFAULT='gsed'
else
    ATNXPI_SED_DEFAULT='sed'
fi
if [[ -z "${ATNXPI_SED+x}" ]]; then
    export ATNXPI_SED="${ATNXPI_SED_DEFAULT}"
fi

# GNU tar
if [[ "${ATNXPI_OS}" == 'osx' ]]; then
    ATNXPI_TAR_DEFAULT='gtar'
else
    ATNXPI_TAR_DEFAULT='tar'
fi
if [[ -z "${ATNXPI_TAR+x}" ]]; then
    export ATNXPI_TAR="${ATNXPI_TAR_DEFAULT}"
fi

# ATN-XPIHandler add-on ID
ATNXPI_ADDON_ID_DEFAULT='atn-xpihandler@celenity.dev'
if [[ -z "${ATNXPI_ADDON_ID+x}" ]]; then
    # By default, use "atn-xpihandler@celenity.dev" for the add-on ID
    export ATNXPI_ADDON_ID="${ATNXPI_ADDON_ID_DEFAULT}"
fi
